questions =  [
    {"id": 0, "question": "After serving their punishment, ones crimes should not be held against them.", "effects": {"mod": -1}},
    {"id": 1, "question": "The idea of Lower-Level Courts is flawed.", "effects": {"fed": -1}},
    {"id": 2, "question": "We should not be afraid to implement taxes if necessary.", "effects": {"ali": -1}},
    {"id": 3, "question": "The General Assembly should be the only legislative body that may vote on bills.", "effects": {"mod": 1}},
    {"id": 4, "question": "The general community should be prioritized over individual rights.", "effects": {"fed": 1}},
    {"id": 5, "question": "Integrating the economy further into the Mock Government will create economic activity.", "effects": {"ali": 1}},
    {"id": 6, "question": "Reform should be the top priority of any Presidential administration.", "effects": {"mod": -1}},
    {"id": 7, "question": "The electoral college election system is inherently flawed.", "effects": {"fed": -1}},
    {"id": 8, "question": "Mock Government businesses should pay a portion of their profit in taxes to the treasury to create a stronger national bank.", "effects": {"ali": -1}},
    {"id": 9, "question": "Court discussion channels should be private.", "effects": {"mod": 1}},
    {"id": 10, "question": "We should revisit and readd old parts of the Mock Government.", "effects": {"fed": 1}},
    {"id": 11, "question": "Economic activity will be better sparked by promoting individual activity than by instating group policies such as taxation.", "effects": {"ali": 1}},
    {"id": 12, "question": "The Bureau of Elections should be run by the Mock Government only.", "effects": {"mod": -1}},
    {"id": 13, "question": "We need to provide and utilize monetary institutions.", "effects": {"ali": -1}},
    {"id": 14, "question": "The courts should be given less power.", "effects": {"mod": 1}},
    {"id": 15, "question": "Regions were implemented well in the Third Republic.", "effects": {"fed": 1}},
    {"id": 16, "question": "A regular loss of money via taxation in the economy will reduce incentive to participate in the economy.", "effects": {"ali": 1}},
    {"id": 17, "question": "Jolly singlehandedly enabled the instability on September 29th, 2021.", "effects": {"mod": -1}},
    {"id": 18, "question": "Regions should be brought back.", "effects": {"fed": 1}},
    {"id": 19, "question": "Reforming the shop is not an effective way to create economic activity.", "effects": {"ali": -1}},
    {"id": 20, "question": "Long term goals are more important than short term goals.", "effects": {"mod": 1}},
    {"id": 21, "question": "Elected Senators and Governors should pay more attention to the needs of their constituents than to the needs of their party.", "effects": {"fed": 1}},
    {"id": 22, "question": "Role income benefits the economy.", "effects": {"ali": 1}},
    {"id": 23, "question": "Effective communication with staff will never benefit the Mock Government.", "effects": {"mod": -1}},
    {"id": 24, "question": "The Bureau of Elections should be publically viewable.", "effects": {"mod": -1}},
    {"id": 25, "question": "The Mock Government should be significantly downsized.", "effects": {"mod": -1}},
    {"id": 26, "question": "The staff team is interfering too much in affairs of the Mock Government.", "effects": {"mod": -1}},
    {"id": 27, "question": "Territories should be self-governing", "effects": {"fed": 1}},
    {"id": 28, "question": "Canada should breakoff from the national government.", "effects": {"fed": 1}},
    {"id": 29, "question": "Canada has too much autonomy.", "effects": {"fed": 1}},
];
